#!/usr/bin/bash

alias Mysql="mysql --defaults-file=/usr/people/wagenaa/.mysql/ontwrd.cnf"



declare -a years=("2008" "2009" "2010" "2011" "2012" "2013" "2014" "2015" "2016")

for i in "${years[@]}"; do
    
    echo "CREATE TABLE waqua_work.eps06511_$i LIKE waqua.eps06511_$i | Mysql ;"
    echo "INSERT waqua_work.eps06511_$i SELECT * FROM waqua.eps06511_$i | Mysql;"
done
