#!/bin/bash

while [ X${1#*=} != X${1} ]; do
  eval $1
  shift
done

: ${myCnf:=ontwrd.cnf}
: ${db:=waqua}
loc=$(statid -one code ${loc:-06514})

#alias Mysql='mysql --defaults-file=$HOME/.mysql/$myCnf'

# set -x
# Mysql -Nse "SHOW TABLES"
# Mysql -e "DESCRIBE eps06514_2017" $db


( for ((yy = 2008; $yy < 2018; yy++)); do
    printf "SELECT %4d, tfmin, tfmax, astro, surge, round(avg((hmean - hobs) / sigma), 2),\n" $yy
    printf "       round(avg(max(hmean - hobs)), 2)" 
#- ((max(avg(sigma)))*(avg(hmean-hobs)/sigma)), 2)\n"
    printf "  FROM eps%5s_%04d\n" $loc $yy
    printf "      JOIN corr\n"
    printf "        ON (code = %s\n" $loc
    printf "       AND tf > tfmin AND tf <= tfmax\n"
    printf "       AND astro = SIGN(hastr)\n"
    printf "       AND surge = SIGN(hmean))\n"
    printf "    WHERE (month(tastr) < 4 OR month(tastr) > 8)\n"
    printf "      AND sigma > 0\n"
    printf "      AND hobs IS NOT NULL\n"
    printf "    GROUP BY tfmin, astro, surge;\n"
  done
) \
  | mysql --defaults-file=$HOME/.mysql/$myCnf -Ns $db
